/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analysis/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_analysis__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{run_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_analysis__run_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/demo/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo */
        post: operations["demo_analysis_demo__patient_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Demo */
        get: operations["list_demo_patients_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_patients_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbstentionState */
        AbstentionState: {
            /** Abstained */
            abstained: boolean;
            /** Reason Code */
            reason_code?: string | null;
            /** Reason Text */
            reason_text?: string | null;
            /** What Would Help */
            what_would_help?: string[];
            /** Sections Rendered */
            sections_rendered?: string[];
        };
        /** AlmanacCombinationOut */
        AlmanacCombinationOut: {
            /** Drug A */
            drug_a: string;
            /** Drug B */
            drug_b: string;
            /** Combination */
            combination: string;
            /** Aligned Cell Lines */
            aligned_cell_lines: number;
            /** Aligned Cell Line Names */
            aligned_cell_line_names?: string | null;
            /** Aligned Median Almanac Combo Score */
            aligned_median_almanac_combo_score?: number | null;
            /** Aligned Pair Support */
            aligned_pair_support?: number | null;
            /** Component Support */
            component_support?: number | null;
            /** Q2 Percentile A */
            q2_percentile_a?: number | null;
            /** Q2 Percentile B */
            q2_percentile_b?: number | null;
            /** Combination Priority */
            combination_priority?: number | null;
            /** Cell Line Alignment Confidence */
            cell_line_alignment_confidence?: string | null;
            /** Interpretation */
            interpretation?: string | null;
            /** Rank */
            rank?: number | null;
        };
        /** AnalysisProgressOut */
        AnalysisProgressOut: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Current Stage */
            current_stage?: string | null;
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["AnalysisStageOut"][];
            /** Error Message */
            error_message?: string | null;
        };
        /** AnalysisResultOut */
        AnalysisResultOut: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Patient Label */
            patient_label: string;
            patient_metadata: components["schemas"]["PatientMetadata"];
            /** Administered Regimen */
            administered_regimen: string[];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Signature Params */
            signature_params?: {
                [key: string]: number;
            } | null;
            cluster_prediction?: components["schemas"]["ClusterPredictionOut"] | null;
            rna_projection?: components["schemas"]["RnaProjectionOut"] | null;
            cluster_signature?: components["schemas"]["SignaturePanelOut"] | null;
            residual_signature?: components["schemas"]["SignaturePanelOut"] | null;
            /**
             * Overlap Nominations
             * @default []
             */
            overlap_nominations: components["schemas"]["OverlapNominationOut"][];
            /**
             * Overlap Exploratory
             * @default []
             */
            overlap_exploratory: components["schemas"]["OverlapNominationOut"][];
            /**
             * Overlap Technical Excluded
             * @default []
             */
            overlap_technical_excluded: components["schemas"]["OverlapNominationOut"][];
            /** Display Gate Summary */
            display_gate_summary?: {
                [key: string]: unknown;
            } | null;
            /** Compound Registry Version */
            compound_registry_version?: string | null;
            /** Analysis Summary */
            analysis_summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Clinical Comparators
             * @default []
             */
            clinical_comparators: {
                [key: string]: unknown;
            }[];
            /**
             * Predictor Single Drugs
             * @default []
             */
            predictor_single_drugs: {
                [key: string]: unknown;
            }[];
            /**
             * Predictor Combinations
             * @default []
             */
            predictor_combinations: {
                [key: string]: unknown;
            }[];
            /** Predictor Summary */
            predictor_summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Near Consensus
             * @default []
             */
            near_consensus: {
                [key: string]: unknown;
            }[];
            /** Overlap Summary */
            overlap_summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Almanac Combinations
             * @default []
             */
            almanac_combinations: components["schemas"]["AlmanacCombinationOut"][];
            /**
             * List1 Drugs
             * @default []
             */
            list1_drugs: {
                [key: string]: unknown;
            }[];
            /**
             * List2 Drugs
             * @default []
             */
            list2_drugs: {
                [key: string]: unknown;
            }[];
            administered_regimen_pcr?: components["schemas"]["SupportedPcrResult"] | null;
            /**
             * Top Candidate Drugs
             * @default []
             */
            top_candidate_drugs: components["schemas"]["DrugCandidate"][];
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["WarningOut"][];
            /** Error Message */
            error_message?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            prototype?: components["schemas"]["PrototypePayload"] | null;
            /** Schema Version */
            schema_version?: string | null;
            /**
             * S4 Ships
             * @default false
             */
            s4_ships: boolean;
        };
        /** AnalysisStageOut */
        AnalysisStageOut: {
            /** Stage Id */
            stage_id: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed";
            /** Detail */
            detail?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** AnalysisSubmitAck */
        AnalysisSubmitAck: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Poll Url */
            poll_url?: string | null;
        };
        /** ApplicabilityGate */
        ApplicabilityGate: {
            /** Represented */
            represented: boolean;
            /** Gate Passed */
            gate_passed: boolean;
            /** Reason */
            reason?: string | null;
            /** Regimen Label */
            regimen_label?: string | null;
            /** Validated Cohort */
            validated_cohort?: string | null;
            /** Validated Split */
            validated_split?: string | null;
            /** Held Out Auroc */
            held_out_auroc?: number | null;
            /** Gate Threshold */
            gate_threshold?: number | null;
        };
        /** ClinicalDiscrepancy */
        ClinicalDiscrepancy: {
            /** Field */
            field: string;
            /** Clinical */
            clinical: string;
            /** Inferred */
            inferred: string;
            /**
             * Severity
             * @default note
             */
            severity: string;
        };
        /** ClusterBadge */
        ClusterBadge: {
            /** Label */
            label: number;
            /** Posterior Mass */
            posterior_mass: number;
        };
        /** ClusterPredictionOut */
        ClusterPredictionOut: {
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Top Cluster */
            top_cluster: number;
            /** Top Probability */
            top_probability: number;
            /**
             * Confidence Level
             * @enum {string}
             */
            confidence_level: "high" | "moderate" | "low" | "abstain";
            /** Gene Coverage */
            gene_coverage: number;
            /** Genes Found */
            genes_found: number;
            /** Genes Requested */
            genes_requested: number;
            /**
             * Method Used
             * @enum {string}
             */
            method_used: "signature_similarity" | "elastic_net";
            /** Warnings */
            warnings: string[];
        };
        /** CompositionPart */
        CompositionPart: {
            /** Cell Type */
            cell_type: string;
            /** Fraction */
            fraction: number;
            /** Ci */
            ci?: number[];
        };
        /** DemoPatientSummary */
        DemoPatientSummary: {
            /** Patient Id */
            patient_id: string;
            /** Role */
            role: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Modalities */
            modalities?: string[];
            /** Expected State */
            expected_state?: number | null;
        };
        /**
         * DrugCandidate
         * @description One nominated drug with every evidence component kept separate --
         *     there is deliberately no single overall score or tier.
         */
        DrugCandidate: {
            /** Drug */
            drug: string;
            /** Targets */
            targets: string[];
            gctx_evidence?: components["schemas"]["GctxDrugEvidence"] | null;
            q2_evidence?: components["schemas"]["Q2DrugEvidence"] | null;
            /** Literature Summary */
            literature_summary?: components["schemas"]["TargetLiteratureCount"] | {
                [key: string]: unknown;
            } | null;
            /**
             * Is In Administered Regimen
             * @default false
             */
            is_in_administered_regimen: boolean;
            /** Evidence Tier */
            evidence_tier?: string | null;
            /** List1 Percentile */
            list1_percentile?: number | null;
            /** List2 Percentile */
            list2_percentile?: number | null;
            /** Indication Bucket */
            indication_bucket?: string | null;
            /** Robustness */
            robustness?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** GctxClusterEvidence */
        GctxClusterEvidence: {
            /** Cluster Id */
            cluster_id: number;
            /** Cluster Probability */
            cluster_probability: number;
            /** Drug Rank */
            drug_rank: number;
            /** Reversal Score */
            reversal_score: number;
            /** Percentile */
            percentile: number;
            /** N Signatures */
            n_signatures: number | null;
            /** Targets */
            targets: string[];
            /** N Drugs In Cluster */
            n_drugs_in_cluster: number;
        };
        /** GctxDrugEvidence */
        GctxDrugEvidence: {
            /** Drug */
            drug: string;
            /** Blended Percentile */
            blended_percentile: number | null;
            /** Clusters With Data */
            clusters_with_data: number;
            /** Per Cluster */
            per_cluster: components["schemas"]["GctxClusterEvidence"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModalityValue */
        ModalityValue: {
            /** Modality */
            modality: string;
            /** Present */
            present: boolean;
            /** Posterior Width Reduction */
            posterior_width_reduction?: number | null;
        };
        /** MolecularState */
        MolecularState: {
            /** Pathways */
            pathways?: components["schemas"]["PathwayActivity"][];
            /** Transcription Factors */
            transcription_factors?: components["schemas"]["TranscriptionFactor"][];
            /** Discrepancies */
            discrepancies?: components["schemas"]["ClinicalDiscrepancy"][];
        };
        /** OverlapNominationOut */
        OverlapNominationOut: {
            /** Drug */
            drug: string;
            /** Canonical */
            canonical: string;
            /** List1 Percentile */
            list1_percentile?: number | null;
            /** List2 Percentile */
            list2_percentile?: number | null;
            /** Weaker Percentile */
            weaker_percentile?: number | null;
            /** Stronger Percentile */
            stronger_percentile?: number | null;
            /** Rank Product */
            rank_product?: number | null;
            /** List1 Rank */
            list1_rank?: number | null;
            /** List2 Rank */
            list2_rank?: number | null;
            /**
             * Targets
             * @default []
             */
            targets: string[];
            /** Evidence Tier */
            evidence_tier?: string | null;
            /** Indication Bucket */
            indication_bucket?: string | null;
            /** Robustness */
            robustness?: {
                [key: string]: unknown;
            } | null;
            /** Q2 Annotation */
            q2_annotation?: {
                [key: string]: unknown;
            } | null;
            /** Literature Summary */
            literature_summary?: {
                [key: string]: unknown;
            } | null;
            /**
             * Is In Administered Regimen
             * @default false
             */
            is_in_administered_regimen: boolean;
            /** Nomination Rank */
            nomination_rank?: number | null;
            /** Support Class */
            support_class?: ("breast_cell_line_supported" | "suggestive" | "excluded_low_confidence") | null;
            /** Support Rank */
            support_rank?: number | null;
            /** Human Development Status */
            human_development_status?: string | null;
            /** Human Development Label */
            human_development_label?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Display Action */
            display_action?: ("default_visible" | "exploratory_only" | "technical_excluded") | null;
            /** Display Gate Reason */
            display_gate_reason?: string | null;
            /** Registry Match Key */
            registry_match_key?: string | null;
        };
        /** PathwayActivity */
        PathwayActivity: {
            /** Name */
            name: string;
            /** Activity */
            activity: number;
            /** Z */
            z?: number | null;
        };
        /**
         * PatientMetadata
         * @description Oncology metadata. Extra demo-enriched fields are allowed and preserved.
         */
        PatientMetadata: {
            /** Age At Diagnosis */
            age_at_diagnosis?: number | null;
            /** Er Status */
            er_status?: string | null;
            /** Her2 Status */
            her2_status?: string | null;
            /** Pr Status */
            pr_status?: string | null;
            /** Claudin Subtype */
            claudin_subtype?: string | null;
            /** Histological Subtype */
            histological_subtype?: string | null;
            /** Lymph Nodes Positive */
            lymph_nodes_positive?: number | null;
            /** Menopausal State */
            menopausal_state?: string | null;
            /** Nottingham Prognostic Index */
            nottingham_prognostic_index?: number | null;
            /** Tumor Stage */
            tumor_stage?: string | null;
            /** Tumor Grade */
            tumor_grade?: number | null;
            /** Tumor Size Mm */
            tumor_size_mm?: number | null;
            /** Ecog Status */
            ecog_status?: number | null;
            /** Prior Therapy */
            prior_therapy?: string | null;
            /** Organ Function */
            organ_function?: {
                [key: string]: unknown;
            } | null;
            /** Location */
            location?: {
                [key: string]: unknown;
            } | null;
            /** Field Provenance */
            field_provenance?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** PatientPosition */
        PatientPosition: {
            /** Umap Coords */
            umap_coords: number[];
            posterior_ellipse: components["schemas"]["PosteriorEllipse"];
            cluster: components["schemas"]["ClusterBadge"];
            /**
             * Cohort Density Ref
             * @default tcga_brca_v2
             */
            cohort_density_ref: string;
            /** Modalities Used */
            modalities_used?: string[];
            /** Cohort Points */
            cohort_points?: {
                [key: string]: unknown;
            }[];
            /** Posterior Width */
            posterior_width?: number | null;
            /** Tau */
            tau?: number | null;
        };
        /** PosteriorEllipse */
        PosteriorEllipse: {
            /** Rx */
            rx: number;
            /** Ry */
            ry: number;
            /** Theta */
            theta: number;
        };
        /** PredictionSet */
        PredictionSet: {
            /**
             * Coverage Level
             * @default 0.9
             */
            coverage_level: number;
            /** Set Members */
            set_members?: components["schemas"]["SetMember"][];
            /** Set Width Note */
            set_width_note?: string | null;
            /**
             * Excluded Count
             * @default 0
             */
            excluded_count: number;
            /** N Scored */
            n_scored?: number | null;
        };
        /** PrototypePayload */
        PrototypePayload: {
            /**
             * Schema Version
             * @default v2_prototype
             * @constant
             */
            schema_version: "v2_prototype";
            /** Patient Id */
            patient_id: string;
            /** Role */
            role: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /**
             * State
             * @default 1
             */
            state: number;
            /** Banner */
            banner?: string | null;
            /** Modalities Present */
            modalities_present?: string[];
            /** Patient Metadata */
            patient_metadata?: {
                [key: string]: unknown;
            };
            sample_quality: components["schemas"]["SampleQuality"];
            position: components["schemas"]["PatientPosition"];
            molecular_state: components["schemas"]["MolecularState"];
            prediction_set?: components["schemas"]["PredictionSet"] | null;
            /** Modality Value Estimate */
            modality_value_estimate?: components["schemas"]["ModalityValue"][];
            abstention: components["schemas"]["AbstentionState"];
            /**
             * S4 Ships
             * @default false
             */
            s4_ships: boolean;
            /** Limitations */
            limitations?: string[];
        };
        /** Q2DrugEvidence */
        Q2DrugEvidence: {
            /** Drug */
            drug: string;
            /** Raw Score */
            raw_score: number | null;
            /** Z Score */
            z_score: number | null;
            /** Genes Used */
            genes_used: number;
            /** Evidence Category */
            evidence_category?: string | null;
            /** Model Support */
            model_support?: number | null;
            /** Model Spearman */
            model_spearman?: number | null;
            /** External Spearman */
            external_spearman?: number | null;
        };
        /** RnaProjectionOut */
        RnaProjectionOut: {
            /** Method */
            method: string;
            /** Label */
            label: string;
            /** Patient */
            patient: {
                [key: string]: number;
            };
            /**
             * Reference
             * @default []
             */
            reference: {
                [key: string]: unknown;
            }[];
            /** N Reference Total */
            n_reference_total?: number | null;
            /** N Reference Shown */
            n_reference_shown?: number | null;
            /** Genes Used */
            genes_used?: number | null;
            /** Gene Coverage */
            gene_coverage?: number | null;
        };
        /** SampleQuality */
        SampleQuality: {
            /** Tumour Fraction */
            tumour_fraction: number;
            /** Composition */
            composition?: components["schemas"]["CompositionPart"][];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "sufficient" | "marginal" | "insufficient";
            /** Verdict Reason */
            verdict_reason?: string | null;
        };
        /** SetMember */
        SetMember: {
            /** Drug */
            drug: string;
            /**
             * Evidence Tier
             * @default B
             */
            evidence_tier: string;
        };
        /** SignatureGeneOut */
        SignatureGeneOut: {
            /** Gene */
            gene: string;
            /** Effect */
            effect: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
            /** Pval */
            pval?: number | null;
            /** Fdr */
            fdr?: number | null;
            /** Literature Count */
            literature_count?: number | null;
        };
        /** SignaturePanelOut */
        SignaturePanelOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "cluster" | "residual";
            /** Cluster Id */
            cluster_id: number;
            /** Top Up */
            top_up: number;
            /** Top Down */
            top_down: number;
            /** N Up */
            n_up: number;
            /** N Down */
            n_down: number;
            /**
             * Genes
             * @default []
             */
            genes: components["schemas"]["SignatureGeneOut"][];
            /** Coverage Fraction */
            coverage_fraction?: number | null;
            /** Genes Used */
            genes_used?: number | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** SupportedPcrResult */
        SupportedPcrResult: {
            applicability_gate: components["schemas"]["ApplicabilityGate"];
            /** Mofa Regimen Reversal Percentile */
            mofa_regimen_reversal_percentile: number | null;
            /** Mofa Regimen Reversal Note */
            mofa_regimen_reversal_note: string;
            /** Pcr Probability */
            pcr_probability: number | null;
            /** Q2 Regimen Score */
            q2_regimen_score: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TargetLiteratureCount
         * @description Legacy compact counts plus V2 retrieved-reference summary fields.
         */
        TargetLiteratureCount: {
            /** Drug */
            drug?: string | null;
            /** Total Citations */
            total_citations?: number | null;
            /** Supporting */
            supporting?: number | null;
            /** Conflicting */
            conflicting?: number | null;
            /** Neutral */
            neutral?: number | null;
            /** Unclear */
            unclear?: number | null;
            /** Retrieved Relevant References */
            retrieved_relevant_references?: number | null;
            /** Stance Counts */
            stance_counts?: {
                [key: string]: number;
            } | null;
            /** Dominant Stance */
            dominant_stance?: string | null;
            /** Note */
            note?: string | null;
            /** Unavailable Reason */
            unavailable_reason?: string | null;
            /** Cache Hit */
            cache_hit?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** TranscriptionFactor */
        TranscriptionFactor: {
            /** Name */
            name: string;
            /** Activity */
            activity: number;
            /**
             * Reliability
             * @default high
             */
            reliability: string;
            /** Reliability Reason */
            reliability_reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarningOut */
        WarningOut: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "caution" | "abstain";
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_analysis_analysis__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_analysis__run_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_analysis_demo__patient_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSubmitAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_demo_patients_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoPatientSummary"][];
                };
            };
        };
    };
    glossary_patients_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
